services:
  mealsync-app:
    image: ${DOCKER_HUB_USERNAME}/mealsync-app:latest
    container_name: mealsync-app
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${RDS_ENDPOINT}:${RDS_PORT}/${RDS_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${RDS_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${RDS_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_CONFIG_LOCATION=classpath:/application.properties,file:/app/env.properties
    volumes:
      - ./env.properties:/app/env.properties
