services:
  mealsync-app:
    image: ${DOCKER_HUB_USERNAME}/mealsync-app:latest
    container_name: mealsync-app
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-instance-mealsync.c5go6284y0dd.eu-north-1.rds.amazonaws.com:${DB_PORT}/${POSTGRES_Docker_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_Docker_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_Docker_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_CONFIG_LOCATION=classpath:/application.properties,file:/app/env.properties
    volumes:
      - /home/ubuntu/mealsync/env.properties:/app/env.properties